# python train.py <config_file_path> <random_seed>
# Example : python3 train.py config/example.yaml 123
    
# GPU Acceleration
USE_GPU : True

# EXPLORATION POLICY
EPSILON_START: 1.0
EPSILON_FINAL: 0.01
EPSILON_DECAY: 500

# NEURAL NETWORK PARAMETERS
HIDDEN_LAYER_WIDTH: 128
BATCH_SIZE: 32


# DRL PARAMETERS
TIMESTEPS: 1_000_000
REPLAY_BUFFER: 'Naive' # 'NaivePrioritized'
REPLAY_BUFFER_SIZE: 1000
TARGET_UPDATE_FREQ: 100
GAMMA: 0.99

# MODEL
# D1QN : Single network DQN
# DQN : Two network DQN with frozen target model
# D2QN: Double DQN
# DuDQN: DQN with Dueling Architecture
# DuD2QN: Double DQN with Dueling Architecture

MODEL_NAME: 'D2QN' #'D2QN' 'D1QN' 'DQN' 'DuDQN' 'DuD2QN'
OPTIMIZER: 'Adam' #'SGD'
LEARNING_RATE: 0.1
CRITERION: 'MSE' #'HUBER'