# python train.py <config_file_path> <random_seed>
# Example : python3 train.py config/example.yaml 123
    
# GPU Acceleration
USE_GPU : True

# EXPLORATION POLICY
EPSILON_START: 1.0
EPSILON_FINAL: 0.01
EPSILON_DECAY: 500

# NEURAL NETWORK PARAMETERS
HIDDEN_LAYER_WIDTH: 128
BATCH_SIZE: 32


# DRL PARAMETERS
TIMESTEPS: 10_000 #10_000 100_000
REPLAY_BUFFER: 'NaivePER' #'Naive', 'NaivePER'
REPLAY_BUFFER_SIZE: 100_000 # 1_000 100_000
TARGET_UPDATE_FREQ: 1_000 # 100
GAMMA: 0.99

# MODEL
# DQN : Two network DQN with frozen target model
# D1QN : Single network DQN
# D2QN: Double DQN
# DuDQN: DQN with Dueling Architecture
# DuD2QN: Double DQN with Dueling Architecture

MODEL_NAME: 'DQN' #'D2QN' 'D1QN' 'DQN' 'DuDQN' 'DuD2QN'
OPTIMIZER: 'Adam' #'SGD'
LEARNING_RATE: 0.001
CRITERION: 'MSE' #'HUBER'

# RUNNING TIME WITH GPU ACCEL
# DQN   : 2min 50sec
# D1QN  : 2min 49sec
# D2QN  : 3min 3sec
# DuDQN : 4min 5sec
# DuD2QN: 4min 17sec